#!/usr/bin/env python3
#
# Writes .clangd, so that an editor's language server parses this tree
# the way the compiler does.
#
# The build is clean under -Wall -Werror and needs none of this.  What
# needs it is clangd, which otherwise falls back to the host toolchain:
# a cross-GCC's own include directories are implicit, so they never
# appear in compile_commands.json, and without them clangd cannot find
# <cstring>.  Everything downstream of that failure is noise - size_t
# reported unknown, SVF reported abstract, hardware headers missing -
# and it is noise that looks exactly like a real defect.
#
# Not part of the build, and .clangd is not committed: the paths below
# name a particular toolchain at a particular version, so the file is
# only ever right for the machine that generated it.  Run this after
# installing or upgrading arm-none-eabi-gcc.

import re
import subprocess
import sys

def system_includes(driver, lang):
    """The compiler's own header directories, which only it knows."""
    p = subprocess.run([driver, "-x", lang, "-E", "-Wp,-v", "-"],
                       input="", capture_output=True, text=True)
    if p.returncode != 0:
        sys.exit("%s failed - is the toolchain on PATH?" % driver)
    m = re.search(r"#include <\.\.\.> search starts here:\n(.*?)\nEnd of search",
                  p.stderr, re.S)
    if not m:
        sys.exit("could not parse the include search list from %s" % driver)
    return [line.strip() for line in m.group(1).splitlines() if line.strip()]


# C and C++ get separate blocks rather than one shared list.  The
# tempting shortcut - name the C++ driver once and let it cover both -
# makes clangd parse the .c files as C++, and every one of them then
# reports "-std=gnu11 not allowed with C++".  Nothing here overrides the
# compiler either: compile_commands.json already names the right driver
# per file, and only the implicit include paths are missing.
HEADER = """\
# Generated by utils/clangd_config.py - editor configuration only, and
# not a build input.  Do not commit it: the paths below name one
# toolchain at one version.  Regenerate with
#
#     python3 utils/clangd_config.py
#
# -Werror is dropped because clangd's warnings are not the compiler's,
# and a language server that reports everything as an error is worse
# than one that reports nothing.
"""

BLOCK = """
If:
  PathMatch: %s
CompileFlags:
  Add: [%s]
  Remove: [-Werror]
"""

out = [HEADER]
# The language standards have to be stated rather than inherited.  CMake
# omits -std when the compiler's own default already matches, so the
# flag is simply absent from compile_commands.json - and clangd's
# default is not GCC's.  Without it a header opened on its own will not
# even admit to C++11, and <string_view> goes missing from the Pimoroni
# graphics headers.  Keep these in step with CMAKE_C_STANDARD and
# CMAKE_CXX_STANDARD in CMakeLists.txt.
c_paths = system_includes("arm-none-eabi-gcc", "c")
cxx_paths = system_includes("arm-none-eabi-g++", "c++")

# Headers get a block of their own, and are forced to C++.  Left to
# itself clangd takes a .h opened on its own for C, and this tree's
# headers are mostly C++ - dsp.h and midi.h include <cstdint>, which
# libstdc++ then rejects outright for want of C++11.  Forcing the other
# way costs nothing, because every header here is already included from
# some .cxx and so has to parse as C++ regardless.
for pattern, flags in (
        (r".*\.c", ["-std=gnu11"] + c_paths),
        (r".*\.(cxx|cpp|cc)", ["-std=gnu++17"] + cxx_paths),
        (r".*\.(h|hpp)", ["-xc++-header", "-std=gnu++17"] + cxx_paths)):
    flags = ["--target=arm-none-eabi"] + [
        f if f.startswith("-") else "-isystem" + f for f in flags]
    out.append(BLOCK % (pattern, ",\n    ".join(flags)))

open(".clangd", "w").write("---".join(out))
print("wrote .clangd")
