// The oscillator wavetables, computed at startup.
//
// These used to be generated by utils/waves.js.  They were always in
// RAM - the generator emitted them without const - so computing them
// here costs nothing extra in RAM and saves the whole image in flash.
// Only the sine needs real maths; the other three are arithmetic.
//
// Unlike the tables in tables.c, these are read once per *sample* per
// voice, indexed directly by phase in Voice::oscillators.  That is why
// they stay in RAM rather than being made const: the access pattern is
// scattered across the table at whatever phase each voice happens to be
// at, which is the worst case for an XIP cache.
//
// Note that saw_table's *contents* are now dead: Voice::oscillators
// derives a saw from the phase accumulator for either oscillator, so
// nothing dereferences it.  It is still built because waves[] is
// indexed by wave number and the entry has to be a valid pointer -
// 4 KB of RAM that could be reclaimed by pointing waves[SAW] at
// another table, which has not been done.

#include <math.h>
#include <stdint.h>

#include "waves.h"

static int16_t sine_table[WAVE_LEN];
static int16_t square_table[WAVE_LEN];
static int16_t saw_table[WAVE_LEN];
static int16_t tri_table[WAVE_LEN];

int16_t* waves[] = {
	sine_table,
	square_table,
	saw_table,
	tri_table,
};

void waves_init(void)
{
	const int half    = WAVE_LEN / 2;
	const int quarter = WAVE_LEN / 4;

	// the ramps step by exactly this per sample, which is what makes
	// saw and triangle span the full int16_t range without a divide
	const int step = 65536 / WAVE_LEN;

	for (int i = 0; i < WAVE_LEN; ++i) {
		sine_table[i] = (int16_t)floorf(32767.0f *
			sinf(2.0f * (float)M_PI * i / WAVE_LEN));

		square_table[i] = (i < half) ? 32767 : -32768;

		saw_table[i] = (int16_t)(32767 - i * step);

		tri_table[i] =
			(i < quarter)     ? (int16_t)(i * 2 * step) :
			(i < 3 * quarter) ? (int16_t)(32767 - 2 * step * (i - quarter))
			                  : (int16_t)(-32768 + 2 * step * (i - 3 * quarter));
	}
}
